apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: health-check-analysis
spec:
  metrics:
    - name: status-check
      successCondition: result == 0
      failureCondition: result != 0
      provider:
        job:
          template:
            spec:
              containers:
                - name: status-check
                  image: curlimages/curl:latest
                  command: [ "sh", "-c" ]
                  args:
                    - |
                      exit 0;
              restartPolicy: Never
