kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: health-check-analysis
spec:
  metrics:
  - name: health-check-analysis
    count: 1
    interval: 5s
    failureLimit: 1
    provider:
      job:
        spec:
          template:
            spec:
              containers:
              - name: health-check-analysis
                image: curlimages/curl:8.9.1
                command: [sh, -c]
                args:
                    - |
                      if [ $(curl -s -o /dev/null -w "%{http_code}" http://192.168.65.3:31826/status) -eq 200 ]; 
                      then exit 0; 
                      else exit 1; 
                      fi
              restartPolicy: Never
          backoffLimit: 0