kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: health-check-analysis
spec:
  metrics:
  - name: health-check-analysis
    count: 1
    interval: 5s
    failureLimit: 1
    provider:
      job:
        spec:
          template:
            spec:
              containers:
              - name: health-check-analysis
                image: curlimages/curl:8.9.1
                command: [sh, -c]
                args:
                    - |
                        HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://argo-test-service-preview/api/status)
                        echo "HTTP Status Code: $HTTP_STATUS"
                        if [ $HTTP_STATUS -eq 200 ]; then
                          echo "Health check passed."
                          exit 0
                        else
                          echo "Health check failed with status code $HTTP_STATUS."
                          exit 1
                        fi
              restartPolicy: Never
          backoffLimit: 0