apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-test-app
  namespace: teste
spec:
  project: default  # Especifique o projeto aqui, "default" é o padrão
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/renamed/ArgoTest.git'
    targetRevision: main
    path: './'
  syncPolicy:
    automated:
      prune: true       # Remove resources no longer defined in Git
      selfHeal: true    # If a resource is modified, Argo CD will revert it
