apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: argo-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argo-test
  template:
    metadata:
      labels:
        app: argo-test
    spec:
      containers:
      - name: argo-test
        image: renamedrj/argotest:29
        ports:
        - containerPort: 8080
  strategy:
    blueGreen:
      activeService: argo-test-service
      previewService: argo-test-service-preview
      autoPromotionEnabled: true
      scaleDownDelaySeconds: 30
      prePromotionAnalysis:
        templates:
          - templateName: health-check-analysis

