apiVersion: v1
kind: Service
metadata:
  name: argo-test-service-preview
spec:
  selector:
    app: argo-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 31826
  type: NodePort
